---

single_shell: true

paths:
  - apps
  - apps_data
  - badusb
  - dolphin
  - gpio
  - infrared
  - nfc
  - rfid
  - subghz
  - subplaylist
  - swd_scripts


repos:
  - repo: https://github.com/logickworkshop/Flipper-IRDB
    path: infrared/flipper-irdb
    post_update:
      - echo "Hello World"

  - repo: https://github.com/I-Am-Jakoby/Flipper-Zero-BadUSB
    path: badusb/I-Am-Jakoby

  - repo: https://github.com/FalsePhilosopher/badusb
    path: badusb/FalsePhilosopher

  # - repo: https://github.com/developer/project
  #   branch: main
  #   subdirectory: /path/to/folder
  #   path: optional/path/to/clone/to

  # - repo: https://github.com/developer/foo@bar#subdirectory=biz
  #   path: subghz/buz
